services:
  db:
    image: postgres:15-alpine
    container_name: db_optic
    restart: always
    environment:
      POSTGRES_PASSWORD: optic_pass
    volumes:
      - ./data/db:/var/lib/postgresql/data # CAMBIO: Datos ahora viven dentro de la carpeta del proyecto
    ports:
      - "5432:5432"

  backend:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: api_optic
    restart: always
    volumes:
      - ./OpticBackend:/app
    working_dir: /app
    ports:
      - "127.0.0.2:80:8080"
    command: /bin/bash -c "dotnet watch run --urls http://0.0.0.0:8080"
    depends_on:
      - db

  frontend:
    image: node:20-alpine
    container_name: web_optic
    restart: always
    volumes:
      - ./OpticFrontend:/app
    working_dir: /app
    ports:
      - "127.0.0.3:80:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend
